// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/signalcd/signalcd/api/v1/models"
)

// AgentsReader is a Reader for the Agents structure.
type AgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewAgentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAgentsOK creates a AgentsOK with default headers values
func NewAgentsOK() *AgentsOK {
	return &AgentsOK{}
}

/*AgentsOK handles this case with default header values.

OK
*/
type AgentsOK struct {
	Payload []*models.Agent
}

func (o *AgentsOK) Error() string {
	return fmt.Sprintf("[GET /agents][%d] agentsOK  %+v", 200, o.Payload)
}

func (o *AgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAgentsInternalServerError creates a AgentsInternalServerError with default headers values
func NewAgentsInternalServerError() *AgentsInternalServerError {
	return &AgentsInternalServerError{}
}

/*AgentsInternalServerError handles this case with default header values.

internal server error
*/
type AgentsInternalServerError struct {
}

func (o *AgentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /agents][%d] agentsInternalServerError ", 500)
}

func (o *AgentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
